[tool.ruff]
target-version = "py39"
line-length = 120

[tool.ruff.lint]
ignore-init-module-imports = true
select = ["A", "E", "F", "I", "N", "Q", "U", "T100"]

[tool.ruff.lint.isort]
known-first-party = ["upid"]

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["py"]
strict = ["py/**"]
reportUnnecessaryTypeIgnoreComment = true
reportUnusedCallResult = false
pythonVersion = "3.9"
pythonPlatform = "Linux"
