name: py

on:
  push:
    tags:
      - '*'
    branches: [ main ]
    paths:
      - 'py/**'
      - 'pyproject.toml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          version: '0.34.0'
      - name: pin version
        run: rye pin 3.12.3
      - name: Sync
        run: |
          rye sync
          if [[ $(git diff --stat requirements.lock) != '' ]]; then
            echo 'Rye lockfile not up-to-date'
            git diff requirements.lock
            exit 1
          fi
      - name: Format
        run: rye fmt --check
      - name: Lint
        run: rye lint
      - name: Typecheck
        run: rye run check
      - name: Test
        run: rye run test

  publish:
    needs: test
    environment: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: softprops/action-gh-release@v1

      - name: Build
        run: |
          pip install build
          python -m build

      - name: Publish
        # mimics: twine upload dist/* --skip-existing
        uses: pypa/gh-action-pypi-publish@release/v1
