name: py

on:
  push:
    tags:
      - '*'
    branches: [ main ]
    paths:
      - 'py/**'
      - 'pyproject.toml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          version: '0.34.0'
      - name: pin version
        run: rye pin 3.12.3
      - name: Sync
        run: |
          rye sync
          if [[ $(git diff --stat requirements.lock) != '' ]]; then
            echo 'Rye lockfile not up-to-date'
            git diff requirements.lock
            exit 1
          fi
      - name: Format
        run: rye fmt --check
      - name: Lint
        run: rye lint
      - name: Typecheck
        run: rye run check
      - name: Test
        run: rye run test
