name: rust

on:
  push:
    tags:
      - '*'
    branches: [ main ]
    paths:
      - 'upid_rs/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy
      - name: Test
        run: cargo test --all-features

  publish:
    needs: test
    environment: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: set version
        env:
          RELEASE_TAG: ${{ github.ref }}
        run: |
          sed -i "s/0\\.0\\.999/${RELEASE_TAG##*\/v}/" Cargo.toml
          sed -i "s/0\\.0\\.999/${RELEASE_TAG##*\/v}/" Cargo.lock

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
      - name: publish
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: |
          cargo publish --token $CRATES_TOKEN --allow-dirty
